# Base model L1: clipped target (p97) → MAE-optimal median prediction.
LGBM_BASE_PARAMS: dict = {
    "objective":         "regression_l1",
    "metric":            "l1",
    "n_estimators":      1400,
    "learning_rate":     0.025,
    "num_leaves":        95,
    "min_child_samples": 25,
    "max_depth":         -1,
    "max_bin":           127,
    "path_smooth":       0.1,
    "feature_fraction":  0.80,
    "bagging_fraction":  0.85,
    "bagging_freq":      5,
    "reg_alpha":         0.05,
    "reg_lambda":        0.20,
    "random_state":      42,
    "n_jobs":            1,
    "num_threads":       1,
    "verbose":           -1,
}

# Base model L2: uncapped target → MSE-optimal mean prediction.
# Because NEM prices are heavy-tailed, E[Y] > median(Y), so the L2 model
# inherently captures upside risk. Blending L1+L2 (Lago et al. 2021) reduces
# both MAE and RMSE simultaneously across all forecast horizons.
LGBM_BASE_L2_PARAMS: dict = {
    "objective":         "regression",
    "metric":            "rmse",
    "n_estimators":      1200,
    "learning_rate":     0.025,
    "num_leaves":        95,
    "min_child_samples": 25,
    "max_depth":         -1,
    "max_bin":           127,
    "path_smooth":       0.1,
    "feature_fraction":  0.80,
    "bagging_fraction":  0.85,
    "bagging_freq":      5,
    "reg_alpha":         0.05,
    "reg_lambda":        0.20,
    "random_state":      43,
    "n_jobs":            1,
    "num_threads":       1,
    "verbose":           -1,
}

# Spike classifier: P(price > SPIKE_THRESHOLD).
LGBM_CLF_PARAMS: dict = {
    "objective":          "binary",
    "metric":             "binary_logloss",
    "n_estimators":       500,
    "learning_rate":      0.025,
    "num_leaves":         63,
    "min_child_samples":  15,
    "max_depth":          -1,
    "max_bin":            127,
    "path_smooth":        0.1,
    "feature_fraction":   0.75,
    "bagging_fraction":   0.85,
    "bagging_freq":       5,
    "reg_alpha":          0.02,
    "reg_lambda":         0.15,
    "scale_pos_weight":   7.0,
    "random_state":       42,
    "n_jobs":             1,
    "num_threads":        1,
    "verbose":            -1,
}

# Spike regressor: full price range, spike rows upweighted 10x.
LGBM_SPIKE_PARAMS: dict = {
    "objective":         "regression_l1",
    "metric":            "l1",
    "n_estimators":      500,
    "learning_rate":     0.025,
    "num_leaves":        63,
    "min_child_samples": 12,
    "max_depth":         -1,
    "max_bin":           127,
    "path_smooth":       0.1,
    "feature_fraction":  0.75,
    "bagging_fraction":  0.85,
    "bagging_freq":      5,
    "reg_alpha":         0.02,
    "reg_lambda":        0.15,
    "random_state":      42,
    "n_jobs":            1,
    "num_threads":       1,
    "verbose":           -1,
}

# Upper-tail spike model (P90 quantile regression) for conservative spike ceiling.
LGBM_SPIKE_Q_PARAMS: dict = {
    "objective":         "quantile",
    "alpha":             0.90,
    "metric":            "quantile",
    "n_estimators":      400,
    "learning_rate":     0.025,
    "num_leaves":        63,
    "min_child_samples": 12,
    "max_depth":         -1,
    "max_bin":           127,
    "path_smooth":       0.1,
    "feature_fraction":  0.75,
    "bagging_fraction":  0.85,
    "bagging_freq":      5,
    "reg_alpha":         0.02,
    "reg_lambda":        0.15,
    "random_state":      42,
    "n_jobs":            1,
    "num_threads":       1,
    "verbose":           -1,
}

LGBM_DIP_CLF_PARAMS: dict = {
    "objective":          "binary",
    "metric":             "binary_logloss",
    "n_estimators":       400,
    "learning_rate":      0.025,
    "num_leaves":         63,
    "min_child_samples":  15,
    "max_depth":          -1,
    "max_bin":            127,
    "path_smooth":        0.1,
    "feature_fraction":   0.75,
    "bagging_fraction":   0.85,
    "bagging_freq":       5,
    "reg_alpha":          0.02,
    "reg_lambda":         0.15,
    "scale_pos_weight":   6.0,
    "random_state":       42,
    "n_jobs":             1,
    "num_threads":        1,
    "verbose":            -1,
}

LGBM_DIP_PARAMS: dict = {
    "objective":         "regression_l1",
    "metric":            "l1",
    "n_estimators":      400,
    "learning_rate":     0.025,
    "num_leaves":        63,
    "min_child_samples": 12,
    "max_depth":         -1,
    "max_bin":           127,
    "path_smooth":       0.1,
    "feature_fraction":  0.75,
    "bagging_fraction":  0.85,
    "bagging_freq":      5,
    "reg_alpha":         0.02,
    "reg_lambda":        0.15,
    "random_state":      42,
    "n_jobs":            1,
    "num_threads":       1,
    "verbose":           -1,
}
